# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
<<<<<<< HEAD
title: 1sm23
subtitle: 1sm的博客
description: 记录牢骚
keywords: 刘时满 personal blog 1sm 1sm23
author: lsm
=======
title: gromit1sm'b1og
subtitle: lsm的博客
description: 记录一点自以为了不起的东西，偶尔发牢骚
keywords: lsm personal blog
author: 
>>>>>>> 639e78ebb02e14308b4c0af3ca5d40bef9241bd7
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
Plugins:
- hexo-generator-feed
- hexo-generator-sitemap
feed:
  type: atom
  path: atom.xml
  limit: 20
#sitemap
sitemap:
  path: sitemap.xml
## Themes: https://hexo.io/themes/
theme: yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: ssh://root@198.181.43.42:26022/root/git/hexo.git
  branch: master
<<<<<<< HEAD
- type: git
  repo: https://github.com/1sm23/1sm23.github.io.git
  branch: master

=======
>>>>>>> 639e78ebb02e14308b4c0af3ca5d40bef9241bd7
jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
<<<<<<< HEAD
      tags: true
#rss插件
plugin:
- hexo-generator-feed

# Feed Atom
feed:
type: atom
path: atom.xml
limit: 20
=======
      tags: true
>>>>>>> 639e78ebb02e14308b4c0af3ca5d40bef9241bd7
